version: '3'

services:
  node:
    image: node:14
    ports:
      - '8080:8080'
    volumes:
      - ./app:/srv/app
    working_dir: /srv/app
    command: 'npm run serve '

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: personal_page_web:prod
    ports:
      - '8080:80'
    profiles:
      - prod
